### ISSUE TITLE
Question text sometimes displayed in the question table, breaking layout for teachers/admins

### ISSUE THREAD

**Issue by dionysius** [studentquiz/moodle-mod_studentquiz#366] opened 2021-12-15 09:28 UTC
Received a contributor notification on the moodle plugin portal with link to the moodle forum: https://moodle.org/mod/forum/discuss.php?d=429999

Looks like question text gets printed, which shouldn't, and this breaks the width of the table

**Comment by cdipe** [comment] 2022-01-03 10:53
@dionysius hi, have you been able to reproduce the problem?

**Comment by dionysius** [comment] 2022-01-03 11:09
I haven't and I'm not involved that much anymore. StudentQuiz is maintaned now by the Open University UK (see [release notes](https://github.com/studentquiz/moodle-mod_studentquiz/releases/tag/v4.5.0)). I just copied the issue here as this is the right place and for better visibility.

**Comment by cdipe** [comment] 2022-01-03 11:58
@dionysius thank you, I understand.
@timhunt do you know if this is reproducible, or are just I having this problem?

**Comment by timhunt** [comment] 2022-01-07 13:21
Sorry, I don't know. I will ask one of my colleauges who knows more about StudentQuiz to take a look.

**Comment by nguyenphuctien** [comment] 2022-01-08 04:55
Hi @cdipe,

I did a quick check. The weird layout is caused by the 'Show question text' option as Tim said (And this is the different I found in your screenshot). This option is loaded from user preference (so it can be set for each users). It can also come from the url params (you can add '&qbshowtext=1' and check with any question bank pages).

Could you please help me to check and confirm if the same issue is happen when you add '&qbshowtext=1' to the url, and check the user's setting for this option again?

**Comment by cdipe** [comment] 2022-01-10 06:55
hi @nguyenphuctien yes, when adding &qbshowtext=1 to the URL as an Admin, the text shows. And, when adding &qbshowtext=0 to the URL when logged in as a Student, the text disappears. But where is this setting in the personal preferences, I have only found the "Show question text in the question list" setting in the Question bank, where Student cannot go.

**Comment by cdipe** [comment] 2022-01-12 12:01
@nguyenphuctien is this only with us, or is it reproducible?

**Comment by nguyenphuctien** [comment] 2022-01-12 12:11
Hi @cdipe,

First, Moodle don't have a UI for student to view or update their user preference. I just guess student click on a question bank link with &qbshowtext=1 and the setting is save to their account. This setting is from the question bank (not studentquiz), and it share between all courses and activities. Our studentquiz is using question bank view to show the questions, so maybe it did not come from your studentquiz activity.

You can create a studentquiz link with &qbshowtext=0 and send to your students. When they click on the link one time, the setting will be save and turn off in the future.

**Comment by cdipe** [comment] 2022-01-12 12:57
@nguyenphuctien thank you! 
If possible, I think this should be managed automatically, if possible. I realise that the question bank and StudentQuiz are tightly integrated, though. 
We (and I think most universities) have loads of teachers who are also students, and high level students who sometimes acts as teachers in low level courses, so this (even though not a bug) will continue to cause confusion.

**Comment by cdipe** [comment] 2022-01-12 13:04
@nguyenphuctien sorry, forget the previous reply. I solved it with CSS:
body#page-mod-studentquiz-view td.questiontext {
    display:none;
}

**Comment by nguyenphuctien** [comment] 2022-01-12 13:16
@cdipe, yes, hide the .questiontext can solve your problem incase you do not need the question text and its display is just an accident.
@timhunt How do you think about the user preference to show the question text? Some users, who can not change this setting by UI, can change it via the url parameters accidentally. Should we set it to hide as default if the user do not have the capability to change the setting in UI? If yes, we have to do it in the question bank.

**Comment by dionysius** [comment] 2022-01-12 17:14
https://github.com/studentquiz/moodle-mod_studentquiz/blob/master/classes/question/bank/question_name_column.php#L77 the question name column still uses the original display of the questionbank. We could write our own there

**Comment by timhunt** [comment] 2022-01-14 09:40
So, acutally, should we just remove that class and all references to it?

**Comment by cdipe** [comment] 2022-01-14 11:58
@dionysius @timhunt I'm quite happy with the question text being hidden completely (as with an CSS solution), but maybe a handy toggle button would serve teachers better; they might have use of being able to see the question text?

**Comment by dionysius** [comment] 2022-01-14 13:10
@cdipe that's a wonderful workaround, were trying to fix this completely for everyone.

@timhunt I guess so. I rembered there was a place where all the colums are defined and found it. At least I've never intended to display the question text with so many colums we have now. My guess is the overrides are not enough there and the inheritance still slips some original code through. Instead of looking into the inheritance, my idea would really be trying to remove that column altogether.

**Comment by timhunt** [comment] 2022-01-14 13:34
@dionysius I agree.

**Comment by timhunt** [comment] 2022-05-26 14:30
This was fixed in https://github.com/studentquiz/moodle-mod_studentquiz/pull/399, and that will be included in the next release. Marking this done.

**Closed** 2022-05-26 19:06 UTC
