### ISSUE TITLE
Language localization in status notifications to students

### ISSUE THREAD

**Issue by cdipe** [studentquiz/moodle-mod_studentquiz#376] opened 2022-01-25 10:34 UTC
(I'm not sure if this has been solved in later versions, we use 4.4.2)
In the StudentQuiz Digest Notification to students the status word is in English, the rest of the text is localized.

Sample in Swedish:
"Din fråga Vilka djur gör vad? i StudentQuizet StudentQuiz: Att arbeta med IKT och lärande vid Lnu i kursen Demo StudentQuiz har blivit **disapproved** av Anonym ansvarig, 25 januari 2022, 10:56."

Also, there is a (minor but still) language problem concerning alla singular and plural statuses. 
For instance, "Approved", "Disapproved" etc are the same in singular and plural when in English, but in Swedish (my language) one question is "Godkänd" (approved) and multiple questions are "Godkända". This concerns all the statuses: When filtering questions the plural word is needed, but when setting the status and in the notifications there should be the singular word.

**Comment by timhunt** [comment] 2022-01-25 10:37
Is this the same as https://github.com/studentquiz/moodle-mod_studentquiz/issues/373 ? 

(The fix for that was just integrated, but not released yet.)

**Comment by cdipe** [comment] 2022-01-25 10:40
@timhunt I'm not sure. 
But the only problem I found in the message was the status word, "Approved", "Disapproved" etc. The rest of the message was in correct Swedish.

**Comment by lucaboesch** [comment] 2022-01-25 10:50
I can confirm, @timhunt, that this is not #373.
@cdipe note that you can improve this yourself. The string state_approved | studentquiz is not translated in sv.
You can contribute to the translation by using the https://lang.moodle.org page or translate this in your own Moodle instance (Sharing it with the whole swedish speaking community by contributing this in https://lang.moodle.org would be lovely though).

You can close that one, Tim.

**Comment by lucaboesch** [comment] 2022-01-25 10:52
Ah. I see. It is about creating a appovedplural and approvedsingular / disappovedplural and disapprovedsingular string.
That doesn't change the fact that tate_approved | studentquiz is not translated in sv is not translated in AMOS (https://lang.moodle.org).

**Comment by cdipe** [comment] 2022-01-25 10:59
Hi @lucaboesch, I have translated the whole package in my installation (except the privacy statements, which we don't). But it seems that state_approved and the other statuses don't end up in the notifications.
![image](https://user-images.githubusercontent.com/14754240/150964366-a972699b-73ca-4b44-8140-c94b67c47e6f.png)
I intend to upload the language pack when I'm done.

**Comment by cdipe** [comment] 2022-01-25 12:36
@lucaboesch if you decide to add plural/singular statuses, that goes for all the question statuses. In the filter it should be plural, and in the question settings and notifications it should be singular.

![image](https://user-images.githubusercontent.com/14754240/150977809-09483aa6-08e7-47e8-bbe6-440ad6b6dc25.png)

**Comment by lucaboesch** [comment] 2022-01-25 13:49
I have to disagree, @cdipe.
If you turn on displaying the string origins and you pass strings=1 as parameter to the url you should see what I see:

![grafik](https://user-images.githubusercontent.com/377279/150988958-ac3ac0c0-714f-4401-9842-5fea1ba5df36.png)

**Comment by cdipe** [comment] 2022-01-25 15:47
Sorry @lucaboesch , we mixed up the topics: In the mail notifications, the statuses are not translated. Otherwise they work fine (but should need singular/plural).
Do you get German statuses in the mail notifications?

In the image above I had changed to English, to also show that - now my grammatics fail me - the status actions have different 'timings' (in lack of better words for it): _Changed_, _Approved_ and _Disapproved_ should be _Change_, _Approve_ and _Disapprove, I think._

Very neat trick with showing the strings, I didn't know of it! When having set to Swedish it looks like this:
![image](https://user-images.githubusercontent.com/14754240/151009628-445c27cb-da4f-4251-bba0-b3450d125fa4.png)

**Comment by lucaboesch** [comment] 2022-01-25 16:17
You are right, @cdipe. That isn't translated.

Ihre Frage Please select true in der StudentQuiz-Aktivität Some StudentQuiz im Kurs Kurs mit allen Plugins und Add-Ons wurde von Anonymer Manager um 25. Januar 2022, 17:04 approved.

It's also a valid point, I think, to change

Choose...
Disapproved
Approved
Changed
Hide
Delete

because that is a wild mix of verb (hide, delete) and past participle (disapproved, approved, changed).

Choose...
Disapproved
Approved
Changed
Hidden
Deleted

is more concise in itself. (I think it should be the past pariciple, not the verb, since we are asked to change a status to something.)

That is–I think–the first thing to change, along with the localization of that state in the notification.

Then, when it comes to distinguish the past participle depending on whether it is singular or plural IMHO that should be a seperate issue.

Best,
Luca

**Comment by timhunt** [comment] 2022-01-25 17:20
@cdipe and @lucaboesch, thank you for finding an analysing this problem.

Chris Nelson and I have discussed your suggestion, and we agree with your suggested improvement to the English wording.

If you have time to make a pull request for this, that would be totally awesome, and I will merge it. If not, we will add it to our development backlog. Thanks.

**Comment by cdipe** [comment] 2022-01-26 07:22
@timhunt @lucaboesch Thanks you both!

**Comment by timhunt** [comment] 2022-12-22 17:26
Since I merged Luca's pull request long ago, I think this is fixed. Closing.

**Closed by timhunt** 2022-12-22 17:26 UTC
