### ISSUE TITLE
moodle installation on windows server 2012 r2

### ISSUE THREAD

**Issue by CChopho** [studentquiz/moodle-mod_studentquiz#325] opened 2021-08-04 08:36 UTC
hello everyone I uncounted error during the first installation on Moodle, below is stack trace

DDL sql execution error

More information about this error

It is usually not possible to recover from errors triggered during installation, you may need to create a new database or use a different database prefix if you want to retry the installation.

×Debug info: InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.

Stack trace:
line 492 of \lib\dml\moodle_database.php: ddl_change_structure_exception thrown
line 1098 of \lib\dml\mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 77 of \lib\ddl\database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
line 427 of \lib\ddl\database_manager.php: call to database_manager->execute_sql_arr()
line 372 of \lib\ddl\database_manager.php: call to database_manager->install_from_xmldb_structure()
line 1802 of \lib\upgradelib.php: call to database_manager->install_from_xmldb_file()
line 276 of \admin\index.php: call to install_core()

**Comment by dionysius** [comment] 2021-08-04 19:17
Table creation is purely managed by the Moodle core, also for plugins. I've found this issue on the moodle tracker: https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-69196

There's so far nothing we can do.

**Comment by timhunt** [comment] 2021-08-05 16:20
Closing, for the reasons in the last comment. (I believe the problem is MySQL 10.6, or something. Don't upgrade to that until Moodle supports it.)

**Closed by timhunt** 2021-08-05 16:20 UTC
Labels: upstream
